### PR TITLE
chore(deps)!: upgrade cdktf to 0.8.1

### PR DESCRIPTION
**Pull request by ansgarm**
<a href="https://gitpod.io/#https://github.com/pahud/cdktf-aws-eks/pull/63"></a>

### CODE REVIEW

**Comment by ansgarm** [comment]
Mergify fails with an info about an invalid config and the note `A brownout is planned for the whole December 6th, 2021 day.` (which is today 🎉😄)

**Comment by ansgarm** [comment]
This issue in projen is about upgrading the generated mergify config that fails today: https://github.com/projen/projen/issues/1240

**Comment by ansgarm** [comment]
@pahud can I help with anything to get this merged? 🙂

**Comment by pahud** [comment]
> @pahud can I help with anything to get this merged? 🙂

Sorry I just noticed this. Absolutely! Thank you so much!

**Comment by pahud** [comment]
@ansgarm are you able to take a look at the snapshot testing?

**Comment by ansgarm** [comment]
@pahud Done 👍

**Comment by ansgarm** [comment]
@pahud could you approve running the workflow?

**Pull request merged**
